const btnAgregarCliente = document.querySelector('.agregar-cliente')
const btnModificarCliente = document.querySelector('.modificar-cliente')
const btnEliminarCliente = document.querySelector('.eliminar-cliente')
const btnLocalidades = document.querySelector('.abm-localidades')
const sectionBotonesPrincipales = document.querySelector('.stl-section-botones-principales')
const sectionAgregarCliente = document.querySelector('.stl-section-agregar-cliente')
const sectionModificarCliente = document.querySelector('.stl-section-modificar-cliente')
const sectionEliminarCliente = document.querySelector('.stl-section-eliminar-cliente')
const sectionLocalidades = document.querySelector('.stl-section-localidades')
const btnCancelarAgregar = document.querySelector('.stl-btn-cancelar-agregar')
const btnCancelarModificar = document.querySelector('.stl-btn-cancelar-modificar')
const btnCancelarEliminar = document.querySelector('.stl-btn-cancelar-eliminar')
const btnCancelarLocalidades = document.querySelector('.stl-btn-cancelar-localidades')

btnAgregarCliente.addEventListener('click', () => {
    sectionAgregarCliente.classList.toggle('activo')
    sectionModificarCliente.classList.remove('activo')
    sectionEliminarCliente.classList.remove('activo')
    sectionLocalidades.classList.remove('activo')
    sectionBotonesPrincipales.classList.remove('activo')
})
btnModificarCliente.addEventListener('click', () => {
    sectionAgregarCliente.classList.remove('activo')
    sectionModificarCliente.classList.toggle('activo')
    sectionEliminarCliente.classList.remove('activo')
    sectionLocalidades.classList.remove('activo')
    sectionBotonesPrincipales.classList.remove('activo')
})
btnEliminarCliente.addEventListener('click', () => {
    sectionAgregarCliente.classList.remove('activo')
    sectionModificarCliente.classList.remove('activo')
    sectionEliminarCliente.classList.toggle('activo')
    sectionLocalidades.classList.remove('activo')
    sectionBotonesPrincipales.classList.remove('activo')
})
btnLocalidades.addEventListener('click', () => {
    sectionAgregarCliente.classList.remove('activo')
    sectionModificarCliente.classList.remove('activo')
    sectionEliminarCliente.classList.remove('activo')
    sectionLocalidades.classList.toggle('activo')
    sectionBotonesPrincipales.classList.remove('activo')
})
btnCancelarAgregar.addEventListener('click', () => {
    sectionAgregarCliente.classList.remove('activo')
    sectionModificarCliente.classList.remove('activo')
    sectionEliminarCliente.classList.remove('activo')
    sectionLocalidades.classList.remove('activo')
    sectionBotonesPrincipales.classList.add('activo')
})
btnCancelarModificar.addEventListener('click', () => {
    sectionAgregarCliente.classList.remove('activo')
    sectionModificarCliente.classList.remove('activo')
    sectionEliminarCliente.classList.remove('activo')
    sectionLocalidades.classList.remove('activo')
    sectionBotonesPrincipales.classList.add('activo')
})
btnCancelarEliminar.addEventListener('click', () => {
    sectionAgregarCliente.classList.remove('activo')
    sectionModificarCliente.classList.remove('activo')
    sectionEliminarCliente.classList.remove('activo')
    sectionLocalidades.classList.remove('activo')
    sectionBotonesPrincipales.classList.add('activo')
})
btnCancelarLocalidades.addEventListener('click', () => {
    sectionAgregarCliente.classList.remove('activo')
    sectionModificarCliente.classList.remove('activo')
    sectionEliminarCliente.classList.remove('activo')
    sectionLocalidades.classList.remove('activo')
    sectionBotonesPrincipales.classList.add('activo')
})